"""
Global Countries, Regions/States, and Major Cities Dataset.
Comprehensive coverage for global B2B lead scraping.
"""

EXTRA_LOCATIONS = {
    # ── Middle East & GCC ──
    "Saudi Arabia": {
        "Riyadh Region": ["Riyadh", "Al Kharj", "Dawadmi", "Al Majmaah", "Shaqra", "Zulfi", "Diriyah", "Wadi Al Dawasir", "Al Hareeq", "Huraymila"],
        "Makkah Region": ["Jeddah", "Mecca", "Taif", "Rabigh", "Al Jumum", "Al Lith", "Qunfudhah", "Ranyah", "Al Khurma"],
        "Madinah Region": ["Medina", "Yanbu", "Al Ula", "Badr", "Khaybar", "Al Mahd", "Al Hanakiyah"],
        "Eastern Province": ["Dammam", "Al Khobar", "Dhahran", "Jubail", "Hafr Al-Batin", "Qatif", "Al Ahsa", "Ras Tanura", "Al Hofuf"],
        "Asir Region": ["Abha", "Khamis Mushait", "Bisha", "Muhayil", "Tathlith"],
        "Tabuk Region": ["Tabuk", "Haql", "Al Wajh", "Umluj", "Dhuba", "Tayma"],
        "Qassim Region": ["Buraydah", "Unaizah", "Al Rass", "Al Midhnab"],
        "Hail Region": ["Hail", "Baqaa"],
        "Jizan Region": ["Jizan", "Sabya", "Abu Arish", "Samtah"],
        "Al Jawf Region": ["Sakaka", "Domat Al Jandal", "Al Qurayyat"],
        "Najran Region": ["Najran", "Sharurah"],
        "Northern Borders Region": ["Arar", "Rafha", "Turaif"],
        "Al Baha Region": ["Al Baha", "Baljurashi"],
    },
    "UAE": {
        "Dubai": ["Dubai", "Deira", "Bur Dubai", "Jumeirah", "Al Quoz", "Al Barsha", "Downtown Dubai", "Business Bay", "Dubai Marina", "JLT", "DIFC", "Al Qusais", "Mirdif", "Jebel Ali", "Dubai Investment Park"],
        "Abu Dhabi": ["Abu Dhabi", "Al Ain", "Khalifa City", "Mohammed Bin Zayed City", "Musaffah", "Al Raha", "Baniyas", "Al Mafraq"],
        "Sharjah": ["Sharjah", "Al Majaz", "Industrial Area Sharjah", "Al Qasimia", "Al Taawun", "Muwaileh"],
        "Ajman": ["Ajman", "Al Jurf", "Al Rashidiya", "Al Hamidiya"],
        "Ras Al Khaimah": ["Ras Al Khaimah", "Al Nakheel", "Khuzam"],
        "Fujairah": ["Fujairah", "Dibba Al Fujairah", "Kalba", "Khor Fakkan"],
        "Umm Al Quwain": ["Umm Al Quwain"],
    },
    "Kuwait": {
        "Al Asimah": ["Kuwait City", "Shuwaikh", "Dasman", "Sharq", "Mirqab"],
        "Hawalli": ["Hawalli", "Salmiya", "Rumaithiya", "Jabriya", "Bayan"],
        "Ahmadi": ["Ahmadi", "Fahaheel", "Mangaf", "Mahboula", "Sabah Al Salem"],
        "Farwaniya": ["Farwaniya", "Khaitan", "Ardiya", "Jleeb Al-Shuyoukh"],
        "Al Jahra": ["Al Jahra", "Sulaibiya", "Saad Al Abdullah"],
        "Mubarak Al-Kabeer": ["Mubarak Al-Kabeer", "Qurain", "Adan"],
    },
    "Qatar": {
        "Doha": ["Doha", "Al Sadd", "West Bay", "Lusail", "The Pearl", "Old Airport"],
        "Al Rayyan": ["Al Rayyan", "Al Gharrafa", "Muaither", "Ain Khaled", "Abu Hamour"],
        "Al Wakrah": ["Al Wakrah", "Al Wukair", "Mesaieed"],
        "Al Khor": ["Al Khor", "Al Thakhira"],
        "Umm Salal": ["Umm Salal Ali", "Umm Salal Mohammed"],
    },
    "Bahrain": {
        "Capital Governorate": ["Manama", "Adliya", "Juffair", "Seef", "Sanabis"],
        "Muharraq Governorate": ["Muharraq", "Hidd", "Amwaj Islands", "Busaiteen"],
        "Northern Governorate": ["Budaiya", "Hamad Town", "Saar", "Janabiya"],
        "Southern Governorate": ["Riffa", "Isa Town", "Sitra", "Zallaq"],
    },
    "Oman": {
        "Muscat Governorate": ["Muscat", "Ruwi", "Muttrah", "Seeb", "Bausher", "Al Amarat", "Qurum"],
        "Dhofar Governorate": ["Salalah", "Taqah", "Mirbat"],
        "Al Batinah North": ["Sohar", "Shinas", "Saham", "Liwa"],
        "Al Batinah South": ["Rustaq", "Nakhal", "Barka", "Al Musanaah"],
        "Al Dakhiliyah": ["Nizwa", "Bahla", "Sumail", "Adam"],
        "Al Sharqiyah North": ["Ibra", "Bidiya", "Al Qabil"],
    },
    "Jordan": {
        "Amman Governorate": ["Amman", "Zarqa", "Russeifa", "Sahab", "Wadi Al-Seer", "Sweileh"],
        "Zarqa Governorate": ["Zarqa", "Russeifa", "Azraq", "Dulail"],
        "Irbid Governorate": ["Irbid", "Ramtha", "Mafraq", "Al Husn"],
        "Aqaba Governorate": ["Aqaba"],
        "Balqa Governorate": ["Salt", "Fuheis", "Ain Al Basha"],
    },
    "Lebanon": {
        "Beirut": ["Beirut", "Achrafieh", "Hamra", "Ras Beirut", "Badaro"],
        "Mount Lebanon": ["Baabda", "Jounieh", "Jbeil (Byblos)", "Aley", "Chouf", "Metn"],
        "North Lebanon": ["Tripoli", "Batroun", "Zgharta", "Bcharre"],
        "South Lebanon": ["Sidon (Saida)", "Tyre (Sour)", "Jezzine"],
        "Bekaa": ["Zahle", "Baalbek", "Chtaura", "Rashaya"],
    },
    "Iraq": {
        "Baghdad Governorate": ["Baghdad", "Karkh", "Rusafa", "Sadr City", "Kadhimiya"],
        "Basra Governorate": ["Basra", "Al-Zubair", "Al-Qurnah", "Umm Qasr"],
        "Nineveh Governorate": ["Mosul", "Tel Afar", "Sinjar"],
        "Erbil Governorate": ["Erbil", "Soran", "Koya"],
        "Sulaymaniyah Governorate": ["Sulaymaniyah", "Halabja", "Ranya"],
        "Najaf Governorate": ["Najaf", "Kufa", "Al-Manathera"],
        "Karbala Governorate": ["Karbala", "Ain Al-Tamur"],
    },

    # ── North & South America ──
    "Canada": {
        "Ontario": ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Vaughan", "Kitchener", "Windsor", "Burlington", "Richmond Hill", "Oakville", "Sudbury", "Barrie"],
        "British Columbia": ["Vancouver", "Surrey", "Burnaby", "Richmond", "Kelowna", "Abbotsford", "Victoria", "Coquitlam", "Nanaimo", "Kamloops", "Prince George"],
        "Quebec": ["Montreal", "Quebec City", "Laval", "Longueuil", "Gatineau", "Sherbrooke", "Levis", "Trois-Rivieres", "Terrebonne", "Saint-Jean-sur-Richelieu"],
        "Alberta": ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Airdrie", "Medicine Hat", "Grande Prairie", "Fort McMurray"],
        "Manitoba": ["Winnipeg", "Brandon", "Steinbach", "Thompson"],
        "Saskatchewan": ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw"],
        "Nova Scotia": ["Halifax", "Dartmouth", "Sydney", "Truro"],
        "New Brunswick": ["Moncton", "Saint John", "Fredericton"],
    },
    "Mexico": {
        "Mexico City": ["Mexico City", "Iztapalapa", "Gustavo A. Madero", "Cuauhtemoc", "Coyoacan", "Benito Juarez", "Alvaro Obregon"],
        "Jalisco": ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonala", "Puerto Vallarta", "Ciudad Guzman"],
        "Nuevo Leon": ["Monterrey", "San Pedro Garza Garcia", "Guadalupe", "San Nicolas de los Garza", "Apodaca", "Santa Catarina"],
        "State of Mexico": ["Ecatepec", "Nezahualcoyotl", "Toluca", "Naucalpan", "Tlalnepantla", "Chimalhuacan"],
        "Guanajuato": ["Leon", "Irapuato", "Celaya", "Salamanca", "Guanajuato", "San Miguel de Allende"],
        "Puebla": ["Puebla", "Tehuacan", "San Martin Texmelucan", "Atlixco"],
        "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Playas de Rosarito", "Tecate"],
        "Chihuahua": ["Ciudad Juarez", "Chihuahua", "Delicias", "Cuauhtemoc", "Parral"],
        "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Cordoba", "Poza Rica"],
        "Queretaro": ["Queretaro", "San Juan del Rio", "El Marques", "Corregidora"],
    },
    "Brazil": {
        "Sao Paulo": ["Sao Paulo", "Guarulhos", "Campinas", "Sao Bernardo do Campo", "Santo Andre", "Osasco", "Sao Jose dos Campos", "Ribeirao Preto", "Sorocaba", "Santos"],
        "Rio de Janeiro": ["Rio de Janeiro", "Sao Goncalo", "Duque de Caxias", "Nova Iguacu", "Niteroi", "Belford Roxo", "Campos dos Goytacazes", "Petropolis"],
        "Minas Gerais": ["Belo Horizonte", "Uberlandia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Uberaba"],
        "Parana": ["Curitiba", "Londrina", "Maringa", "Ponta Grossa", "Cascavel", "Foz do Iguacu"],
        "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul", "Canoas", "Pelotas", "Santa Maria", "Gravatai"],
        "Bahia": ["Salvador", "Feira de Santana", "Vitoria da Conquista", "Camacari", "Itabuna"],
        "Santa Catarina": ["Joinville", "Florianopolis", "Blumenau", "Sao Jose", "Chapeco", "Itajai"],
        "Goias": ["Goiania", "Aparecida de Goiania", "Anapolis", "Rio Verde"],
        "Ceara": ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanau"],
        "Pernambuco": ["Recife", "Jaboatao dos Guararapes", "Olinda", "Caruaru", "Petrolina"],
    },
    "Argentina": {
        "Buenos Aires": ["Buenos Aires", "La Plata", "Mar del Plata", "Bahia Blanca", "Quilmes", "Lanus", "San Martin", "Tigre", "Avellaneda"],
        "Cordoba": ["Cordoba", "Villa Maria", "Rio Cuarto", "Carlos Paz", "San Francisco"],
        "Santa Fe": ["Rosario", "Santa Fe", "Rafaela", "Venado Tuerto"],
        "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz", "Guaymallen"],
        "Tucuman": ["San Miguel de Tucuman", "Tafi Viejo", "Concepcion"],
    },
    "Colombia": {
        "Bogota D.C.": ["Bogota", "Suba", "Kennedy", "Engativa", "Usaquen", "Chapinero"],
        "Antioquia": ["Medellin", "Bello", "Itagui", "Envigado", "Rionegro"],
        "Valle del Cauca": ["Cali", "Palmira", "Buenaventura", "Tulua", "Cartago"],
        "Atlantico": ["Barranquilla", "Soledad", "Malambo"],
        "Santander": ["Bucaramanga", "Floridablanca", "Giron", "Barrancabermeja"],
        "Bolivar": ["Cartagena", "Magangue", "Turbaco"],
    },
    "Chile": {
        "Santiago Metropolitan": ["Santiago", "Puente Alto", "Maipu", "La Florida", "Las Condes", "San Bernardo", "Providencia"],
        "Valparaiso": ["Valparaiso", "Vina del Mar", "Quilpue", "Villa Alemana"],
        "Biobio": ["Concepcion", "Talcahuano", "Los Angeles", "Coronel"],
        "Antofagasta": ["Antofagasta", "Calama"],
        "Araucania": ["Temuco", "Padre Las Casas"],
    },
    "Peru": {
        "Lima": ["Lima", "Callao", "San Juan de Lurigancho", "San Martin de Porres", "Miraflores", "San Isidro", "Santiago de Surco"],
        "Arequipa": ["Arequipa", "Cerro Colorado", "Paucarpata"],
        "La Libertad": ["Trujillo", "Victor Larco Herrera", "Huanchaco"],
        "Piura": ["Piura", "Sullana", "Talara"],
        "Cusco": ["Cusco", "Wanchaq", "Santiago"],
    },

    # ── Europe ──
    "UK": {
        "England": ["London", "Birmingham", "Manchester", "Leeds", "Sheffield", "Liverpool", "Bristol", "Leicester", "Coventry", "Nottingham", "Newcastle upon Tyne", "Southampton", "Brighton", "Plymouth", "Derby", "Wolverhampton", "Norwich", "Luton", "Milton Keynes", "Reading", "Northampton", "Portsmouth"],
        "Scotland": ["Glasgow", "Edinburgh", "Aberdeen", "Dundee", "Inverness", "Stirling", "Perth", "Paisley", "East Kilbride"],
        "Wales": ["Cardiff", "Swansea", "Newport", "Wrexham", "Barry", "Bridgend"],
        "Northern Ireland": ["Belfast", "Derry", "Lisburn", "Newry", "Bangor", "Craigavon"],
    },
    "Germany": {
        "Bavaria": ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Ingolstadt", "Wurzburg", "Erlangen", "Bamberg"],
        "North Rhine-Westphalia": ["Cologne", "Dusseldorf", "Dortmund", "Essen", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Munster", "Gelsenkirchen", "Aachen"],
        "Baden-Wurttemberg": ["Stuttgart", "Mannheim", "Karlsruhe", "Freiburg", "Heidelberg", "Ulm", "Heilbronn", "Pforzheim"],
        "Berlin": ["Berlin"],
        "Hamburg": ["Hamburg"],
        "Saxony": ["Leipzig", "Dresden", "Chemnitz", "Zwickau"],
        "Hesse": ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach"],
        "Lower Saxony": ["Hanover", "Braunschweig", "Osnabruck", "Oldenburg", "Wolfsburg", "Gottingen"],
        "Rhineland-Palatinate": ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Kaiserslautern"],
    },
    "France": {
        "Ile-de-France": ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Montreuil", "Versailles", "Nanterre", "Creteil"],
        "Auvergne-Rhone-Alpes": ["Lyon", "Grenoble", "Saint-Etienne", "Clermont-Ferrand", "Villeurbanne", "Annecy"],
        "Provence-Alpes-Cote dAzur": ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Cannes", "Avignon", "Antibes"],
        "Occitanie": ["Toulouse", "Montpellier", "Nimes", "Perpignan", "Beziers"],
        "Nouvelle-Aquitaine": ["Bordeaux", "Limoges", "Pau", "Poitiers", "La Rochelle"],
        "Hauts-de-France": ["Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkerque"],
        "Normandy": ["Rouen", "Caen", "Le Havre"],
        "Grand Est": ["Strasbourg", "Reims", "Metz", "Nancy", "Mulhouse"],
        "Brittany": ["Rennes", "Brest", "Lorient", "Quimper"],
        "Pays de la Loire": ["Nantes", "Le Mans", "Angers", "Saint-Nazaire"],
    },
    "Italy": {
        "Lombardy": ["Milan", "Brescia", "Monza", "Bergamo", "Como", "Varese", "Pavia", "Cremona"],
        "Lazio": ["Rome", "Latina", "Guidonia Montecelio", "Fiumicino", "Viterbo"],
        "Campania": ["Naples", "Salerno", "Giugliano in Campania", "Torre del Greco", "Caserta"],
        "Veneto": ["Venice", "Verona", "Padua", "Vicenza", "Treviso"],
        "Piedmont": ["Turin", "Novara", "Alessandria", "Asti"],
        "Emilia-Romagna": ["Bologna", "Parma", "Modena", "Reggio Emilia", "Ravenna", "Rimini", "Ferrara"],
        "Tuscany": ["Florence", "Prato", "Livorno", "Arezzo", "Pisa", "Lucca"],
        "Sicily": ["Palermo", "Catania", "Messina", "Syracuse", "Marsala"],
        "Puglia": ["Bari", "Taranto", "Foggia", "Lecce", "Brindisi"],
    },
    "Spain": {
        "Madrid": ["Madrid", "Mostoles", "Alcala de Henares", "Fuenlabrada", "Leganes", "Getafe", "Alcorcon"],
        "Catalonia": ["Barcelona", "L'Hospitalet de Llobregat", "Badalona", "Terrassa", "Sabadell", "Mataro", "Tarragona", "Girona", "Lleida"],
        "Andalusia": ["Seville", "Malaga", "Cordoba", "Granada", "Jerez de la Frontera", "Almeria", "Cadiz", "Marbella"],
        "Valencia": ["Valencia", "Alicante", "Elche", "Castellon de la Plana", "Torrevieja"],
        "Galicia": ["Vigo", "A Coruna", "Ourense", "Santiago de Compostela", "Lugo"],
        "Basque Country": ["Bilbao", "Vitoria-Gasteiz", "San Sebastian", "Barakaldo"],
        "Canary Islands": ["Las Palmas", "Santa Cruz de Tenerife", "San Cristobal de La Laguna", "Telde"],
        "Aragon": ["Zaragoza", "Huesca", "Teruel"],
        "Balearic Islands": ["Palma de Mallorca", "Calvia", "Ibiza"],
    },
    "Netherlands": {
        "North Holland": ["Amsterdam", "Haarlem", "Zaanstad", "Alkmaar", "Hilversum", "Amstelveen"],
        "South Holland": ["Rotterdam", "The Hague", "Leiden", "Dordrecht", "Zoetermeer", "Delft", "Gouda"],
        "North Brabant": ["Eindhoven", "Tilburg", "Breda", "'s-Hertogenbosch", "Helmond", "Roosendaal"],
        "Utrecht": ["Utrecht", "Amersfoort", "Veenendaal", "Zeist", "Nieuwegein"],
        "Gelderland": ["Nijmegen", "Arnhem", "Apeldoorn", "Ede"],
        "Overijssel": ["Enschede", "Zwolle", "Deventer", "Hengelo"],
        "Groningen": ["Groningen"],
        "Limburg": ["Maastricht", "Venlo", "Sittard-Geleen", "Heerlen"],
    },
    "Belgium": {
        "Brussels Region": ["Brussels", "Schaerbeek", "Anderlecht", "Ixelles", "Uccle"],
        "Flanders": ["Antwerp", "Ghent", "Bruges", "Leuven", "Mechelen", "Aalst", "Hasselt", "Kortrijk", "Ostend"],
        "Wallonia": ["Charleroi", "Liege", "Namur", "Mons", "La Louviere", "Tournai"],
    },
    "Switzerland": {
        "Zurich": ["Zurich", "Winterthur", "Uster"],
        "Geneva": ["Geneva", "Vernier", "Lancy"],
        "Vaud": ["Lausanne", "Yverdon-les-Bains", "Montreux"],
        "Bern": ["Bern", "Thun", "Biel/Bienne"],
        "Basel-City": ["Basel", "Riehen"],
        "Lucerne": ["Lucerne", "Emmen", "Kriens"],
        "St. Gallen": ["St. Gallen", "Rapperswil-Jona"],
        "Ticino": ["Lugano", "Bellinzona", "Locarno"],
    },
    "Austria": {
        "Vienna": ["Vienna"],
        "Lower Austria": ["Sankt Polten", "Wiener Neustadt", "Krems an der Donau", "Baden"],
        "Upper Austria": ["Linz", "Wels", "Steyr"],
        "Styria": ["Graz", "Leoben", "Kapfenberg"],
        "Tyrol": ["Innsbruck", "Kufstein", "Telfs"],
        "Salzburg": ["Salzburg", "Hallein", "Saalfelden"],
        "Carinthia": ["Klagenfurt", "Villach", "Wolfsberg"],
    },
    "Poland": {
        "Masovian": ["Warsaw", "Radom", "Plock", "Siedlce", "Ostroleka"],
        "Silesian": ["Katowice", "Czestochowa", "Sosnowiec", "Gliwice", "Zabrze", "Bielsko-Biala", "Bytom"],
        "Lesser Poland": ["Krakow", "Tarnow", "Nowy Sacz", "Oswiecim"],
        "Lower Silesian": ["Wroclaw", "Walbrzych", "Legnica", "Jelenia Gora"],
        "Greater Poland": ["Poznan", "Kalisz", "Konin", "Pila", "Ostrow Wielkopolski"],
        "Pomeranian": ["Gdansk", "Gdynia", "Slupsk", "Tczew", "Sopot"],
        "Lodz": ["Lodz", "Piotrkow Trybunalski", "Pabianice", "Tomaszow Mazowiecki"],
        "West Pomeranian": ["Szczecin", "Koszalin", "Stargard"],
    },
    "Sweden": {
        "Stockholm County": ["Stockholm", "Huddinge", "Nacka", "Sodertalje", "Solna", "Taby"],
        "Vastra Gotaland": ["Gothenburg", "Boras", "Trollhattan", "Skovde", "Uddevalla"],
        "Skane County": ["Malmo", "Helsingborg", "Lund", "Kristianstad", "Landskrona"],
        "Uppsala County": ["Uppsala", "Enkoping"],
        "Ostergotland": ["Linkoping", "Norrkoping", "Motala"],
        "Orebro County": ["Orebro", "Karlskoga"],
        "Jonkoping County": ["Jonkoping", "Varnamo", "Nassjo"],
    },
    "Norway": {
        "Oslo": ["Oslo"],
        "Viken": ["Drammen", "Fredrikstad", "Sarpsborg", "Asker", "Barum", "Lillestrom"],
        "Vestland": ["Bergen", "Askoy", "Fjell", "Stord"],
        "Rogaland": ["Stavanger", "Sandnes", "Haugesund", "Sola"],
        "Trondelag": ["Trondheim", "Steinkjer", "Stjordal"],
        "Troms og Finnmark": ["Tromso", "Harstad", "Alta"],
    },
    "Denmark": {
        "Capital Region": ["Copenhagen", "Frederiksberg", "Gentofte", "Gladsaxe", "Helsingor"],
        "Central Denmark": ["Aarhus", "Randers", "Horsens", "Silkeborg", "Herning", "Viborg"],
        "Region of Southern Denmark": ["Odense", "Esbjerg", "Kolding", "Vejle", "Fredericia"],
        "North Denmark": ["Aalborg", "Hjorring", "Frederikshavn"],
        "Region Zealand": ["Roskilde", "Naestved", "Slagelse", "Holbaek", "Koge"],
    },
    "Finland": {
        "Uusimaa": ["Helsinki", "Espoo", "Vantaa", "Porvoo", "Hyvinkaa", "Jarvenpaa"],
        "Pirkanmaa": ["Tampere", "Nokia", "Ylojarvi", "Kangasala"],
        "Southwest Finland": ["Turku", "Salo", "Kaarina", "Raisio"],
        "North Ostrobothnia": ["Oulu", "Raahe", "Kuusamo"],
        "Central Finland": ["Jyvaskyla", "Aanekoski"],
        "Pohjois-Savo": ["Kuopio", "Iisalmi", "Varkaus"],
    },
    "Ireland": {
        "Leinster": ["Dublin", "Dun Laoghaire", "Swords", "Drogheda", "Dundalk", "Kilkenny", "Navan", "Bray"],
        "Munster": ["Cork", "Limerick", "Waterford", "Tralee", "Ennis", "Killarney"],
        "Connacht": ["Galway", "Sligo", "Castlebar", "Ballina"],
        "Ulster (RoI)": ["Letterkenny", "Monaghan", "Cavan"],
    },
    "Portugal": {
        "Lisbon District": ["Lisbon", "Sintra", "Vila Franca de Xira", "Cascais", "Loures", "Amadora", "Almada", "Setubal"],
        "Porto District": ["Porto", "Vila Nova de Gaia", "Matosinhos", "Maia", "Gondomar", "Povoa de Varzim"],
        "Braga District": ["Braga", "Guimaraes", "Vila Nova de Famalicao", "Barcelos"],
        "Coimbra District": ["Coimbra", "Figueira da Foz"],
        "Faro (Algarve)": ["Faro", "Portimao", "Loule", "Albufeira", "Lagos"],
        "Aveiro District": ["Aveiro", "Santa Maria da Feira", "Ovar"],
    },
    "Greece": {
        "Attica": ["Athens", "Piraeus", "Peristeri", "Kallithea", "Glyfada", "Marousi", "Kifisia"],
        "Central Macedonia": ["Thessaloniki", "Kalamaria", "Serres", "Katerini", "Veria"],
        "Crete": ["Heraklion", "Chania", "Rethymno", "Agios Nikolaos"],
        "Thessaly": ["Larissa", "Volos", "Trikala", "Karditsa"],
        "Western Greece": ["Patras", "Agrinio"],
    },
    "Turkey": {
        "Istanbul": ["Istanbul", "Kadikoy", "Besiktas", "Uskudar", "Fatih", "Sisli", "Bakirkoy", "Umraniye", "Beylikduzu", "Basaksehir", "Pendik"],
        "Ankara": ["Ankara", "Cankaya", "Kecioren", "Yenimahalle", "Mamak", "Etimesgut", "Sincan"],
        "Izmir": ["Izmir", "Bornova", "Karsiyaka", "Konak", "Buca", "Cigli", "Gaziemir"],
        "Bursa": ["Bursa", "Osmangazi", "Nilufer", "Yildirim", "Inegol"],
        "Antalya": ["Antalya", "Muratpasa", "Kepez", "Konyaalti", "Alanya", "Manavgat"],
        "Adana": ["Adana", "Seyhan", "Yuregir", "Cukurova"],
        "Gaziantep": ["Gaziantep", "Sahinbey", "Sehitkamil"],
        "Konya": ["Konya", "Selcuklu", "Karatay", "Meram"],
        "Mersin": ["Mersin", "Akdeniz", "Mezitli", "Toroslar", "Yenisehir", "Tarsus"],
        "Kocaeli": ["Izmit", "Gebze", "Darica", "Korfez", "Golcuk"],
    },

    # ── Asia & South Asia ──
    "Pakistan": {
        "Punjab": ["Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Multan", "Sialkot", "Bahawalpur", "Sargodha", "Sheikhupura", "Jhang", "Rahim Yar Khan", "Gujrat", "Kasur", "Sahiwal", "Okara", "Chiniot", "Hafizabad", "Khanewal", "Muzaffargarh", "Attock", "Chakwal", "Jhelum", "Narowal", "Wah Cantonment", "Taxila", "Mandi Bahauddin", "Dera Ghazi Khan", "Burewala", "Vehari"],
        "Sindh": ["Karachi", "Hyderabad", "Sukkur", "Larkana", "Nawabshah", "Mirpurkhas", "Jacobabad", "Khairpur", "Dadu", "Badin", "Thatta", "Kotri", "Sanghar", "Shikarpur", "Ghotki", "Tando Adam"],
        "Khyber Pakhtunkhwa": ["Peshawar", "Mardan", "Mingora", "Kohat", "Abbottabad", "Mansehra", "Dera Ismail Khan", "Swabi", "Charsadda", "Nowshera", "Haripur", "Bannu"],
        "Balochistan": ["Quetta", "Turbat", "Khuzdar", "Hub", "Chaman", "Gwadar", "Loralai", "Sibi"],
        "Islamabad Capital Territory": ["Islamabad"],
        "Azad Kashmir": ["Muzaffarabad", "Mirpur", "Rawalakot", "Kotli", "Bhimber"],
        "Gilgit-Baltistan": ["Gilgit", "Skardu", "Hunza", "Diamer"],
    },
    "India": {
        "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Kolhapur", "Navi Mumbai", "Kalyan-Dombivli", "Vasai-Virar", "Pimpri-Chinchwad"],
        "Delhi": ["New Delhi", "Delhi", "Noida", "Gurugram", "Faridabad", "Ghaziabad", "Greater Noida"],
        "Karnataka": ["Bengaluru", "Mysuru", "Hubli-Dharwad", "Mangaluru", "Belagavi", "Davangere", "Ballari", "Kalaburagi"],
        "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Tiruppur", "Erode", "Vellore"],
        "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Junagadh", "Anand"],
        "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Prayagraj (Allahabad)", "Meerut", "Bareilly", "Aligarh", "Moradabad", "Gorakhpur"],
        "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Bidhannagar", "Kharagpur"],
        "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner", "Bhilwara", "Alwar"],
        "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Secunderabad"],
        "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Kannur", "Alappuzha"],
        "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali"],
        "Haryana": ["Faridabad", "Gurugram", "Panipat", "Ambala", "Karnal", "Hisar", "Rohtak"],
        "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain"],
        "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati"],
    },
    "Japan": {
        "Tokyo": ["Tokyo", "Shinjuku", "Shibuya", "Minato", "Chiyoda", "Chuo", "Koto", "Shinagawa", "Setagaya", "Ota"],
        "Osaka": ["Osaka", "Sakai", "Higashiosaka", "Toyonaka", "Hirakata", "Takatsuki", "Suita"],
        "Kanagawa": ["Yokohama", "Kawasaki", "Sagamihara", "Fujisawa", "Yokosuka", "Hiratsuka"],
        "Aichi": ["Nagoya", "Toyota", "Okazaki", "Ichinomiya", "Toyohashi", "Kasugai"],
        "Saitama": ["Saitama", "Kawaguchi", "Kawagoe", "Tokorozawa", "Koshigaya"],
        "Chiba": ["Chiba", "Funabashi", "Matsudo", "Ichikawa", "Kashiwa"],
        "Hyogo": ["Kobe", "Himeji", "Nishinomiya", "Amagasaki", "Akashi"],
        "Fukuoka": ["Fukuoka", "Kitakyushu", "Kurume", "Iizuka"],
        "Hokkaido": ["Sapporo", "Asahikawa", "Hakodate", "Kushiro", "Obihiro"],
        "Kyoto": ["Kyoto", "Uji", "Kameoka"],
    },
    "South Korea": {
        "Seoul": ["Seoul", "Gangnam", "Seocho", "Songpa", "Mapo", "Jung-gu", "Yeongdeungpo", "Yongsan"],
        "Gyeonggi-do": ["Suwon", "Seongnam", "Goyang", "Yongin", "Bucheon", "Ansan", "Hwaseong", "Namyangju", "Anyang", "Pyeongtaek"],
        "Busan": ["Busan", "Haeundae", "Busanjin", "Sasang", "Saha"],
        "Incheon": ["Incheon", "Songdo", "Bupyeong", "Namdong", "Yeonsu"],
        "Daegu": ["Daegu", "Suseong", "Dalseo", "Buk-gu"],
        "Daejeon": ["Daejeon", "Yuseong", "Seo-gu"],
        "Gwangju": ["Gwangju", "Buk-gu", "Gwangsan"],
        "Gyeongsangnam-do": ["Changwon", "Gimhae", "Jinju", "Yangsan"],
    },
    "China": {
        "Guangdong": ["Guangzhou", "Shenzhen", "Dongguan", "Foshan", "Zhongshan", "Huizhou", "Zhuhai", "Jiangmen", "Shantou"],
        "Shanghai": ["Shanghai", "Pudong", "Minhang", "Baoshan", "Jiading", "Songjiang"],
        "Beijing": ["Beijing", "Chaoyang", "Haidian", "Fengtai", "Daxing", "Tongzhou"],
        "Zhejiang": ["Hangzhou", "Ningbo", "Wenzhou", "Jiaxing", "Shaoxing", "Jinhua", "Taizhou"],
        "Jiangsu": ["Nanjing", "Suzhou", "Wuxi", "Changzhou", "Nantong", "Xuzhou", "Yangzhou", "Taizhou"],
        "Shandong": ["Jinan", "Qingdao", "Yantai", "Weifang", "Zibo", "Jining", "Linyi"],
        "Sichuan": ["Chengdu", "Mianyang", "Nanchong", "Yibin", "Luzhou"],
        "Fujian": ["Fuzhou", "Xiamen", "Quanzhou", "Zhangzhou"],
        "Hubei": ["Wuhan", "Xiangyang", "Yichang", "Jingzhou"],
        "Tianjin": ["Tianjin", "Binhai", "Wuqing", "Hexi"],
    },
    "Singapore": {
        "Singapore": ["Central Area", "Jurong East", "Jurong West", "Woodlands", "Tampines", "Tuas", "Bedok", "Changi", "Yishun", "Ang Mo Kio", "Punggol", "Sengkang"],
    },
    "Malaysia": {
        "Selangor": ["Shah Alam", "Petaling Jaya", "Subang Jaya", "Klang", "Kajang", "Selayang", "Rawang", "Ampang"],
        "Kuala Lumpur": ["Kuala Lumpur", "Cheras", "Kepong", "Bukit Bintang", "Setapak", "Bangsar"],
        "Johor": ["Johor Bahru", "Iskandar Puteri", "Batu Pahat", "Kulai", "Muar", "Kluang", "Pasir Gudang"],
        "Penang": ["George Town", "Butterworth", "Bukit Mertajam", "Bayan Lepas", "Seberang Perai"],
        "Perak": ["Ipoh", "Taiping", "Teluk Intan", "Manjung"],
        "Sabah": ["Kota Kinabalu", "Sandakan", "Tawau"],
        "Sarawak": ["Kuching", "Miri", "Sibu", "Bintulu"],
        "Pahang": ["Kuantan", "Temerloh", "Bentong"],
    },
    "Indonesia": {
        "Jakarta": ["Central Jakarta", "South Jakarta", "West Jakarta", "East Jakarta", "North Jakarta"],
        "West Java": ["Bandung", "Bekasi", "Depok", "Bogor", "Cimahi", "Tasikmalaya", "Cirebon", "Karawang", "Sukabumi"],
        "East Java": ["Surabaya", "Malang", "Sidoarjo", "Gresik", "Kediri", "Jember", "Probolinggo"],
        "Central Java": ["Semarang", "Surakarta (Solo)", "Tegal", "Pekalongan", "Magelang", "Salatiga"],
        "Banten": ["Tangerang", "South Tangerang", "Serang", "Cilegon"],
        "North Sumatra": ["Medan", "Binjai", "Pematangsiantar", "Deli Serdang"],
        "Bali": ["Denpasar", "Badung", "Gianyar", "Kuta", "Sanur"],
        "South Sulawesi": ["Makassar", "Gowa", "Parepare"],
    },
    "Thailand": {
        "Bangkok": ["Bangkok", "Chatuchak", "Bang Na", "Din Daeng", "Sathon", "Watthana", "Khlong Toei"],
        "Central": ["Nonthaburi", "Pak Kret", "Samut Prakan", "Pathum Thani", "Phra Nakhon Si Ayutthaya"],
        "Eastern": ["Chonburi", "Pattaya", "Rayong", "Si Racha", "Laem Chabang"],
        "Northern": ["Chiang Mai", "Chiang Rai", "Phitsanulok", "Nakhon Sawan", "Lampang"],
        "Northeastern (Isan)": ["Nakhon Ratchasima (Korat)", "Khon Kaen", "Udon Thani", "Ubon Ratchathani"],
        "Southern": ["Phuket", "Hat Yai", "Surat Thani", "Songkhla", "Nakhon Si Thammarat"],
    },
    "Philippines": {
        "Metro Manila": ["Manila", "Quezon City", "Makati", "Taguig (BGC)", "Pasig", "Parañaque", "Caloocan", "Muntinlupa", "Las Piñas", "Mandaluyong", "Pasay"],
        "Calabarzon": ["Antipolo", "Dasmarinas", "Bacoor", "Calamba", "Santa Rosa", "Batangas City", "Lipa", "Cabuyao"],
        "Central Luzon": ["San Fernando", "Angeles", "San Jose del Monte", "Mabalacat", "Malolos", "Meycauayan", "Olongapo", "Tarlac City"],
        "Central Visayas": ["Cebu City", "Mandaue", "Lapu-Lapu", "Talisay"],
        "Davao Region": ["Davao City", "Tagum", "Panabo", "Digos"],
        "Western Visayas": ["Iloilo City", "Bacolod"],
    },
    "Vietnam": {
        "Southeast": ["Ho Chi Minh City", "Thu Duc", "Bien Hoa", "Binh Duong (Thu Dau Mot)", "Vung Tau", "Tan An"],
        "Red River Delta": ["Hanoi", "Hai Phong", "Bac Ninh", "Hai Duong", "Nam Dinh", "Vinh Phuc"],
        "South Central Coast": ["Da Nang", "Nha Trang", "Quy Nhon", "Phan Thiet"],
        "Mekong Delta": ["Can Tho", "My Tho", "Long Xuyen", "Rach Gia"],
        "North Central Coast": ["Hue", "Vinh", "Thanh Hoa"],
    },
    "Bangladesh": {
        "Dhaka Division": ["Dhaka", "Gazipur", "Narayanganj", "Tangail", "Narsingdi", "Faridpur"],
        "Chittagong Division": ["Chittagong", "Comilla", "Cox's Bazar", "Feni", "Brahmanbaria", "Chandpur"],
        "Khulna Division": ["Khulna", "Jessore", "Kushtia", "Jhenaidah"],
        "Rajshahi Division": ["Rajshahi", "Bogra", "Pabna", "Naogaon"],
        "Sylhet Division": ["Sylhet", "Moulvibazar", "Habiganj"],
    },
    "Sri Lanka": {
        "Western Province": ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa", "Negombo", "Sri Jayawardenepura Kotte", "Gampaha"],
        "Central Province": ["Kandy", "Matale", "Nuwara Eliya"],
        "Southern Province": ["Galle", "Matara", "Hambantota"],
        "Northern Province": ["Jaffna", "Kilinochchi", "Vavuniya"],
    },

    # ── Africa ──
    "Egypt": {
        "Cairo Governorate": ["Cairo", "Heliopolis", "Nasr City", "New Cairo", "Maadi", "Shubra", "Zamalek"],
        "Giza Governorate": ["Giza", "6th of October City", "Sheikh Zayed", "Dokki", "Agouza", "Haram"],
        "Alexandria Governorate": ["Alexandria", "Smouha", "Montazah", "Borg El Arab", "Miami", "Gleem"],
        "Qalyubia Governorate": ["Banha", "Shubra El Kheima", "Qalyub", "Khanka"],
        "Sharqia Governorate": ["Zagazig", "10th of Ramadan", "Bilbeis", "Faqous"],
        "Dakahlia Governorate": ["Mansoura", "Mit Ghamr", "Talkha", "Sinbillawain"],
        "Gharbia Governorate": ["Tanta", "El Mahalla El Kubra", "Zifta", "Kafr El Zayat"],
        "Suez Governorate": ["Suez", "Ain Sokhna"],
        "Port Said Governorate": ["Port Said", "Port Fouad"],
        "Ismailia Governorate": ["Ismailia", "Fayed", "Qantara"],
        "Red Sea Governorate": ["Hurghada", "Safaga", "El Gouna"],
        "South Sinai Governorate": ["Sharm El Sheikh", "Dahab", "Nuweiba"],
    },
    "Morocco": {
        "Casablanca-Settat": ["Casablanca", "Mohammedia", "El Jadida", "Settat", "Berrechid", "Bouskoura"],
        "Rabat-Sale-Kenitra": ["Rabat", "Sale", "Kenitra", "Temara", "Khemisset", "Sidi Slimane"],
        "Tangier-Tetouan-Al Hoceima": ["Tangier", "Tetouan", "Larache", "Ksar El Kebir", "Al Hoceima"],
        "Marrakech-Safi": ["Marrakech", "Safi", "Essaouira", "El Kelaa des Sraghna"],
        "Fes-Meknes": ["Fes", "Meknes", "Taza", "Zouagha"],
        "Souss-Massa": ["Agadir", "Inezgane", "Ait Melloul", "Taroudant"],
        "Oriental": ["Oujda", "Nador", "Berkane", "Taourirt"],
    },
    "South Africa": {
        "Gauteng": ["Johannesburg", "Pretoria", "Sandton", "Soweto", "Centurion", "Randburg", "Roodepoort", "Midrand", "Kempton Park", "Boni"],
        "Western Cape": ["Cape Town", "Stellenbosch", "George", "Paarl", "Somerset West", "Bellville", "Mossel Bay"],
        "KwaZulu-Natal": ["Durban", "Pietermaritzburg", "Pinetown", "Richards Bay", "Newcastle", "Umhlanga"],
        "Eastern Cape": ["Gqeberha (Port Elizabeth)", "East London", "Uitenhage", "Mthatha"],
        "Free State": ["Bloemfontein", "Welkom", "Sasolburg"],
        "Mpumalanga": ["Mbombela (Nelspruit)", "Witbank (Emalahleni)", "Secunda"],
    },
    "Nigeria": {
        "Lagos State": ["Lagos", "Ikeja", "Lekki", "Victoria Island", "Surulere", "Yaba", "Apapa", "Ikorodu", "Epe", "Agege"],
        "Abuja Federal Capital Territory": ["Abuja", "Garki", "Wuse", "Maitama", "Asokoro", "Gwarinpa", "Kubwa"],
        "Kano State": ["Kano", "Fagge", "Dala", "Gwale", "Nassarawa"],
        "Rivers State": ["Port Harcourt", "Obio-Akpor", "Eleme", "Bonny"],
        "Oyo State": ["Ibadan", "Ogbomosho", "Oyo", "Iseyin"],
        "Kaduna State": ["Kaduna", "Zaria", "Kafanchan"],
        "Ogun State": ["Abeokuta", "Ota", "Sagamu", "Ijebu Ode"],
        "Anambra State": ["Onitsha", "Awka", "Nnewi"],
        "Edo State": ["Benin City", "Uromi", "Auchi"],
    },
    "Kenya": {
        "Nairobi": ["Nairobi", "Westlands", "Kilimani", "Industrial Area", "Karen", "Embakasi", "Kasarani"],
        "Coast": ["Mombasa", "Nyali", "Kilifi", "Malindi", "Diani"],
        "Nyanza": ["Kisumu", "Kisii", "Homa Bay"],
        "Rift Valley": ["Nakuru", "Eldoret", "Naivasha", "Kericho", "Kitale"],
        "Central": ["Thika", "Nyeri", "Kiambu", "Ruiru", "Muranga"],
        "Eastern": ["Machakos", "Meru", "Embu"],
    },

    # ── Oceania ──
    "Australia": {
        "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Maitland", "Albury", "Coffs Harbour", "Wagga Wagga", "Port Macquarie", "Tamworth", "Orange", "Dubbo", "Bathurst"],
        "Victoria": ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton", "Mildura", "Warrnambool", "Wodonga", "Traralgon"],
        "Queensland": ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville", "Cairns", "Toowoomba", "Mackay", "Rockhampton", "Bundaberg", "Hervey Bay", "Gladstone"],
        "Western Australia": ["Perth", "Mandurah", "Bunbury", "Geraldton", "Albany", "Kalgoorlie", "Busselton", "Karratha"],
        "South Australia": ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge", "Port Augusta", "Port Lincoln"],
        "Tasmania": ["Hobart", "Launceston", "Devonport", "Burnie"],
        "Northern Territory": ["Darwin", "Alice Springs", "Palmerston"],
        "Australian Capital Territory": ["Canberra"],
    },
    "New Zealand": {
        "Auckland Region": ["Auckland", "Manukau", "North Shore", "Waitakere", "Pukekohe"],
        "Canterbury": ["Christchurch", "Timaru", "Ashburton", "Rangiora"],
        "Wellington Region": ["Wellington", "Lower Hutt", "Upper Hutt", "Porirua", "Paraparaumu"],
        "Waikato": ["Hamilton", "Taupo", "Cambridge", "Te Awamutu"],
        "Bay of Plenty": ["Tauranga", "Rotorua", "Whakatane"],
        "Otago": ["Dunedin", "Queenstown", "Wanaka", "Oamaru"],
        "Manawatu-Whanganui": ["Palmerston North", "Whanganui", "Feilding"],
        "Hawke's Bay": ["Napier", "Hastings", "Havelock North"],
    },
}
