"""
USA - Top 40 cities per state by population (auto-generated from GeoNames)
"""

LOCATIONS = {
    "USA": {
        "Alabama": [
            "Huntsville", "Birmingham", "Montgomery", "Mobile", "Tuscaloosa", "Hoover",
            "Dothan", "Auburn", "Decatur", "Madison", "Florence", "Phenix City",
            "Gadsden", "East Florence", "Prattville", "Vestavia Hills", "Alabaster", "Opelika",
            "Enterprise", "Bessemer", "Homewood", "Athens", "Daphne", "Northport",
            "Dixiana", "Pelham", "Prichard", "Anniston", "Albertville", "Oxford",
            "Trussville", "Mountain Brook", "Selma", "Troy", "Fairhope", "Helena",
            "Tillmans Corner", "Foley", "Center Point", "Hueytown",
        ],
        "Alaska": [
            "Anchorage", "Fairbanks", "Juneau", "Eagle River", "Badger", "Knik-Fairview",
            "College", "Wasilla", "Sitka", "Lakes", "Ketchikan", "Tanaina",
            "Kalifornsky", "Kenai", "Meadow Lakes", "Palmer", "Elmendorf Air Force Base", "Bethel",
            "Kodiak", "Sterling", "Gateway", "Homer", "Farmers Loop", "Fishhook",
            "Soldotna", "Nikiski", "Unalaska", "Utqiagvik", "Dutch Harbor", "Valdez",
            "Nome", "Big Lake", "Kotzebue", "Butte", "Petersburg", "Seward",
            "Eielson Air Force Base", "Ester", "Dillingham", "Wrangell",
        ],
        "Arizona": [
            "Phoenix", "Tucson", "Mesa", "Chandler", "Gilbert", "Glendale",
            "Scottsdale", "Maryvale", "Peoria", "Tempe", "Deer Valley", "Tempe Junction",
            "Surprise", "Alhambra", "Yuma", "Ahwatukee Foothills", "San Tan Valley", "Avondale",
            "Goodyear", "Flagstaff", "Casas Adobes", "Central City", "Encanto", "Lake Havasu City",
            "Casa Grande", "Buckeye", "Catalina Foothills", "Maricopa", "Oro Valley", "Sierra Vista",
            "Prescott Valley", "Prescott", "Marana", "Bullhead City", "Apache Junction", "Sun City",
            "Queen Creek", "El Mirage", "San Luis", "Florence",
        ],
        "Arkansas": [
            "Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro", "North Little Rock",
            "Conway", "Rogers", "Pine Bluff", "Bentonville", "Hot Springs", "Benton",
            "Sherwood", "Texarkana", "Russellville", "Jacksonville", "Bella Vista", "Paragould",
            "Cabot", "West Memphis", "Searcy", "Van Buren", "Bryant", "El Dorado",
            "Maumelle", "Siloam Springs", "Blytheville", "Forrest City", "Harrison", "Hot Springs Village",
            "Mountain Home", "Marion", "Centerton", "Magnolia", "Camden", "Helena-West Helena",
            "Malvern", "Arkadelphia", "Batesville", "Hope",
        ],
        "California": [
            "Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento",
            "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Riverside", "Santa Ana",
            "Stockton", "Chula Vista", "Irvine", "Fremont", "San Bernardino", "Fontana",
            "Modesto", "Oxnard", "Moreno Valley", "Huntington Beach", "Glendale", "Santa Clarita",
            "Santa Rosa", "Oceanside", "Garden Grove", "Rancho Cucamonga", "Ontario", "Hollywood",
            "Elk Grove", "Corona", "Lancaster", "Palmdale", "Hayward", "Salinas",
            "Sunnyvale", "Pomona", "Escondido", "Valencia",
        ],
        "Colorado": [
            "Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton",
            "Westminster", "Arvada", "Centennial", "Pueblo", "Greeley", "Boulder",
            "Highlands Ranch", "Longmont", "Loveland", "Broomfield", "Grand Junction", "Castle Rock",
            "Commerce City", "Parker", "Littleton", "Southglenn", "Northglenn", "Brighton",
            "Dakota Ridge", "Englewood", "Security-Widefield", "Windsor", "Ken Caryl", "Wheat Ridge",
            "Pueblo West", "Fountain", "Lafayette", "Castlewood", "Columbine", "Erie",
            "Evans", "Louisville", "Golden", "Clifton",
        ],
        "Connecticut": [
            "Bridgeport", "New Haven", "Stamford", "North Stamford", "Hartford", "Waterbury",
            "Norwalk", "Danbury", "East Norwalk", "New Britain", "West Hartford", "Bristol",
            "Meriden", "Hamden", "Fairfield", "West Haven", "Milford", "Stratford",
            "City of Milford (balance)", "East Hartford", "Middletown", "Enfield", "Southington", "Shelton",
            "Norwich", "Trumbull", "West Torrington", "Torrington", "Glastonbury", "Naugatuck",
            "Manchester", "Newington", "Cheshire", "Branford", "East Haven", "Windsor",
            "New London", "Wethersfield", "Mansfield City", "Westport",
        ],
        "Delaware": [
            "Wilmington", "Dover", "Newark", "Middletown", "Bear", "Brookside",
            "Glasgow", "Hockessin", "Smyrna", "Pike Creek Valley", "Milford", "Claymont",
            "North Star", "Pike Creek", "Wilmington Manor", "Seaford", "Georgetown", "Elsmere",
            "Edgemoor", "New Castle", "Millsboro", "Laurel", "Nassau", "Harrington",
            "Camden", "Highland Acres", "Dover Base Housing", "Rising Sun-Lebanon", "Clayton", "Lewes",
            "Milton", "Riverview", "Selbyville", "Greenville", "Woodside East", "Bridgeville",
            "Townsend", "Ocean View", "Long Neck", "Kent Acres",
        ],
        "Florida": [
            "Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah",
            "Tallahassee", "Fort Lauderdale", "Cape Coral", "Pembroke Pines", "Port Saint Lucie", "Hollywood",
            "Gainesville", "Miramar", "Coral Springs", "West Palm Beach", "Palm Bay", "Clearwater",
            "Miami Gardens", "Pompano Beach", "Lakeland", "Brandon", "Davie", "Spring Hill",
            "Boca Raton", "Plantation", "Miami Beach", "Deltona", "Lehigh Acres", "Melbourne",
            "Sunrise", "Palm Coast", "Largo", "Homestead", "Kendall", "Deerfield Beach",
            "Town 'n' Country", "Alafaya", "Doral", "Fort Myers",
        ],
        "Georgia": [
            "Atlanta", "Columbus", "Savannah", "Athens", "South Fulton", "Sandy Springs",
            "Roswell", "Macon", "Johns Creek", "Albany", "Warner Robins", "Alpharetta",
            "Marietta", "Smyrna", "Valdosta", "Brookhaven", "Stonecrest", "Dunwoody",
            "Augusta", "Peachtree Corners", "Gainesville", "Milton", "Newnan", "Mableton",
            "Rome", "Martinez", "East Point", "Peachtree City", "Dalton", "Kennesaw",
            "Hinesville", "Redan", "Douglasville", "Statesboro", "Lawrenceville", "Woodstock",
            "LaGrange", "Duluth", "Evans", "Chamblee",
        ],
        "Hawaii": [
            "Honolulu", "East Honolulu", "Pearl City", "Waiau-Pacific Palisades", "Makakilo / Kapolei / Honokai Hale", "Kalihi-Palama",
            "Hilo", "Joint Base Pearl Harbor Hickam", "Aliamanu / Salt Lakes / Foster Village", "Kailua", "Waipahu", "'Ewa Gentry-West Loch",
            "Kaneohe", "Hawai'i Kai", "Airport", "McCully - Moiliili", "Mililani Town", "Kahului",
            "Liliha - Kapalama", "Mo'ili'ili", "Manoa", "'Ewa Gentry", "Wahiawa-Whitmore", "'Ewa Beach-Iroquois Point",
            "Mililani Mauka", "Makakilo-Makaiwa Hills-Kunia", "Kihei", "Kaimuki", "Kalihi Valley", "Schofield-Wheeler",
            "Waikiki", "Diamond Head / Kapahulu / Saint Louis Heights", "Niu Valley", "Ala Moana - Kaka'ako", "Makakilo", "Mililani Mauka / Launani Valley",
            "Wahiawa", "'Ewa Beach", "Schofield Barracks", "Nuuanu - Punchbowl",
        ],
        "Idaho": [
            "Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello", "Caldwell",
            "Coeur d'Alene", "Twin Falls", "Lewiston", "Lewiston Orchards", "Post Falls", "Rexburg",
            "Moscow", "Eagle", "Conda", "Kuna", "Ammon", "Chubbuck",
            "Hayden", "Mountain Home", "Blackfoot", "Garden City", "Jerome", "Burley",
            "Hailey", "Sandpoint", "Star", "Rathdrum", "Payette", "Middleton",
            "Emmett", "Rupert", "Weiser", "Preston", "Fruitland", "Shelley",
            "American Falls", "Buhl", "Rigby", "Lincoln",
        ],
        "Illinois": [
            "Chicago", "Aurora", "Rockford", "Joliet", "Naperville", "Peoria",
            "Springfield", "North Peoria", "Elgin", "Waukegan", "West Town", "Champaign",
            "Near North Side", "Cicero", "Belmont Cragin", "Bloomington", "Arlington Heights", "Evanston",
            "Schaumburg", "Bolingbrook", "South Lawndale", "Logan Square", "Decatur", "West Ridge",
            "Palatine", "Lincoln Park", "Portage Park", "Skokie", "Des Plaines", "Orland Park",
            "Tinley Park", "Oak Lawn", "Irving Park", "Berwyn", "Chicago Lawn", "Uptown",
            "Edgewater", "Mount Prospect", "Rogers Park", "Normal",
        ],
        "Indiana": [
            "Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Bloomington",
            "Hammond", "Gary", "Fishers", "Lafayette", "Muncie", "Terre Haute",
            "Noblesville", "Kokomo", "Greenwood", "Anderson", "Elkhart", "Mishawaka",
            "Lawrence", "Jeffersonville", "Columbus", "West Lafayette", "Portage", "Westfield",
            "New Albany", "Richmond", "Merrillville", "Goshen", "Valparaiso", "Michigan City",
            "Plainfield", "Granger", "Marion", "Crown Point", "Schererville", "East Chicago",
            "Hobart", "Zionsville", "Brownsburg", "Franklin",
        ],
        "Iowa": [
            "Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "Waterloo",
            "Ames", "West Des Moines", "Council Bluffs", "Dubuque", "Ankeny", "Urbandale",
            "Cedar Falls", "Marion", "Bettendorf", "Marshalltown", "Mason City", "Clinton",
            "Burlington", "Fort Dodge", "Ottumwa", "Muscatine", "Johnston", "Coralville",
            "Waukee", "Altoona", "North Liberty", "Indianola", "Clive", "Newton",
            "Boone", "Oskaloosa", "Spencer", "Storm Lake", "Fort Madison", "Grimes",
            "Keokuk", "Pella", "Norwalk", "Waverly",
        ],
        "Kansas": [
            "Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence",
            "Shawnee", "Manhattan", "Lenexa", "Salina", "Hutchinson", "Leavenworth",
            "Leawood", "Dodge City", "Garden City", "Emporia", "Junction City", "Derby",
            "Prairie Village", "Hays", "Gardner", "Liberal", "Pittsburg", "Newton",
            "Great Bend", "McPherson", "El Dorado", "Andover", "Ottawa", "Winfield",
            "Arkansas City", "Lansing", "Merriam", "Haysville", "Atchison", "Parsons",
            "Coffeyville", "Mission", "Augusta", "Chanute",
        ],
        "Kentucky": [
            "Louisville", "Lexington", "Lexington-Fayette", "Meads", "Bowling Green", "Owensboro",
            "Covington", "Richmond", "Georgetown", "Florence", "Hopkinsville", "Nicholasville",
            "Elizabethtown", "Henderson", "Frankfort", "Jeffersontown", "Independence", "Pleasure Ridge Park",
            "Paducah", "Valley Station", "Radcliff", "Ashland", "Newburg", "Madisonville",
            "Murray", "Erlanger", "Winchester", "Fern Creek", "Saint Matthews", "Okolona",
            "Danville", "Fort Thomas", "Burlington", "Shively", "Newport", "Shelbyville",
            "Highview", "Berea", "Glasgow", "Mount Washington",
        ],
        "Louisiana": [
            "New Orleans", "Baton Rouge", "Shreveport", "Metairie Terrace", "Metairie", "Lafayette",
            "Lake Charles", "Bossier City", "Kenner", "Monroe", "Alexandria", "Houma",
            "Marrero", "New Iberia", "Laplace", "Central", "Slidell", "Prairieville",
            "Terrytown", "Ruston", "Hammond", "Harvey", "Sulphur", "Bayou Cane",
            "Shenandoah", "Natchitoches", "Gretna", "Chalmette", "Opelousas", "Zachary",
            "Estelle", "Thibodaux", "Pineville", "Bayou Boeuf", "Grand Bayou Mobile Home Park", "Baker",
            "River Ridge", "Crowley", "West Monroe", "Minden",
        ],
        "Maine": [
            "Portland", "Lewiston", "Bangor", "West Scarborough", "South Portland", "South Portland Gardens",
            "Auburn", "Biddeford", "Sanford", "Saco", "Augusta", "Westbrook",
            "Waterville", "Brunswick", "York Beach", "Wells Beach Station", "Orono", "Lisbon",
            "North Bath", "Brewer", "Presque Isle", "Old Orchard Beach", "Bath", "Buxton",
            "Ellsworth", "Caribou", "Winslow", "Old Town", "Waterboro", "South Berwick",
            "Rockland", "Gorham", "Belfast", "Eliot", "Skowhegan", "Topsham",
            "Yarmouth", "Gardiner", "Turner", "Lebanon",
        ],
        "Maryland": [
            "Baltimore", "Columbia", "Germantown", "Silver Spring", "Frederick", "Waldorf",
            "Glen Burnie", "Gaithersburg", "Rockville", "Ellicott City", "Dundalk", "Bethesda",
            "Bowie", "Towson", "South Bel Air", "Aspen Hill", "Wheaton", "Bel Air South",
            "Gwynn Oak", "Potomac", "Severn", "North Bethesda", "Catonsville", "Annapolis",
            "Hagerstown", "Essex", "Hanover", "Woodlawn", "Severna Park", "Odenton",
            "Saint Charles", "Clinton", "Oxon Hill-Glassmanor", "North Bel Air", "Olney", "Suitland-Silver Hill",
            "Chillum", "St. Charles", "Salisbury", "Randallstown",
        ],
        "Massachusetts": [
            "Boston", "South Boston", "Worcester", "Springfield", "Lowell", "Cambridge",
            "New Bedford", "Dorchester", "Brockton", "Fall River", "Quincy", "Lynn",
            "Newton", "Somerville", "Lawrence", "Framingham", "Framingham Center", "Waltham",
            "Haverhill", "Malden", "Brookline", "Medford", "Taunton", "Chicopee",
            "North Chicopee", "Weymouth", "Revere", "Peabody", "Methuen", "South Peabody",
            "Barnstable", "Everett", "Brighton", "Attleboro", "Pittsfield", "East Boston",
            "Salem", "Arlington", "Westfield", "Leominster",
        ],
        "Michigan": [
            "Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing",
            "Clinton Township", "Flint", "Dearborn", "Livonia", "Canton", "Troy",
            "Westland", "Farmington Hills", "Kalamazoo", "Waterford", "Wyoming", "Shelby",
            "Rochester Hills", "Southfield", "West Bloomfield Township", "Taylor", "Pontiac", "Saint Clair Shores",
            "Royal Oak", "Novi", "Dearborn Heights", "Battle Creek", "Kentwood", "Redford",
            "Saginaw", "East Lansing", "Portage", "Roseville", "Midland", "Muskegon",
            "Lincoln Park", "Bay City", "Holland", "Jackson",
        ],
        "Minnesota": [
            "Minneapolis", "Saint Paul", "Rochester", "Bloomington", "Duluth", "Brooklyn Park",
            "Plymouth", "Maple Grove", "Woodbury", "Eagan", "Saint Cloud", "Eden Prairie",
            "West Coon Rapids", "Coon Rapids", "Blaine", "Burnsville", "Lakeville", "Minnetonka",
            "Apple Valley", "Edina", "Minnetonka Mills", "Saint Louis Park", "Moorhead", "Mankato",
            "Maplewood", "Shakopee", "Richfield", "Cottage Grove", "Roseville", "Inver Grove Heights",
            "Andover", "Brooklyn Center", "Savage", "Longfellow Community", "Oakdale", "Fridley",
            "Winona", "Shoreview", "Ramsey", "Owatonna",
        ],
        "Mississippi": [
            "Jackson", "Gulfport", "West Gulfport", "Southaven", "Hattiesburg", "Biloxi",
            "Meridian", "Olive Branch", "Tupelo", "Greenville", "Horn Lake", "Pearl",
            "Madison", "Starkville", "Clinton", "Ridgeland", "Brandon", "Columbus",
            "Vicksburg", "Oxford", "Pascagoula", "Laurel", "Gautier", "Ocean Springs",
            "Clarksdale", "Long Beach", "Hernando", "Greenwood", "Natchez", "Corinth",
            "Canton", "Moss Point", "Carriere", "Grenada", "McComb", "Brookhaven",
            "Cleveland", "Byram", "D'Iberville", "Yazoo City",
        ],
        "Missouri": [
            "Kansas City", "St. Louis", "Springfield", "Columbia", "Independence", "East Independence",
            "Lee's Summit", "O'Fallon", "Saint Joseph", "Saint Charles", "Blue Springs", "Saint Peters",
            "Florissant", "Joplin", "Chesterfield", "Jefferson City", "Cape Girardeau", "Oakville",
            "Wildwood", "Wentzville", "University City", "Ballwin", "Liberty", "Raytown",
            "Mehlville", "Kirkwood", "Maryland Heights", "Gladstone", "Hazelwood", "Grandview",
            "Webster Groves", "Belton", "Sedalia", "Arnold", "Ferguson", "Nixa",
            "Raymore", "Affton", "Rolla", "Warrensburg",
        ],
        "Montana": [
            "Billings", "Missoula", "Great Falls", "Bozeman", "Butte", "Helena",
            "Kalispell", "Havre", "Anaconda", "Miles City", "Helena Valley Southeast", "Belgrade",
            "Helena Valley West Central", "Evergreen", "Livingston", "Whitefish", "Laurel", "Sidney",
            "Lockwood", "Lewistown", "Glendive", "Orchard Homes", "Columbia Falls", "Polson",
            "Hamilton", "Bigfork", "Dillon", "Lolo", "Hardin", "Helena Valley Northwest",
            "Malmstrom Air Force Base", "Glasgow", "Shelby", "Four Corners", "Cut Bank", "Warm Springs",
            "Helena Valley Northeast", "Deer Lodge", "Wolf Point", "Montana City",
        ],
        "Nebraska": [
            "Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont",
            "Hastings", "Norfolk", "North Platte", "Columbus", "Papillion", "La Vista",
            "Scottsbluff", "South Sioux City", "Beatrice", "Chalco", "Lexington", "Alliance",
            "Gering", "Elkhorn", "Blair", "York", "McCook", "Nebraska City",
            "Hillsborough", "Seward", "Crete", "Sidney", "Plattsmouth", "Schuyler",
            "Ralston", "Chadron", "Wayne", "Holdrege", "Gretna", "Offutt Air Force Base",
            "Ogallala", "Wahoo", "Aurora", "Falls City",
        ],
        "Nevada": [
            "Las Vegas", "Henderson", "Reno", "North Las Vegas", "Paradise", "Sunrise Manor",
            "Spring Valley", "Enterprise", "Sparks", "Carson City", "Whitney", "Pahrump",
            "Winchester", "Summerlin South", "Elko", "Fernley", "Sun Valley", "Mesquite",
            "Boulder City", "Spanish Springs", "Spring Creek", "Gardnerville Ranchos", "Dayton", "Incline Village",
            "Cold Springs", "Fallon", "Winnemucca", "Laughlin", "Moapa Valley", "Johnson Lane",
            "Gardnerville", "Indian Hills", "Silver Springs", "Lemmon Valley", "West Wendover", "Ely",
            "Battle Mountain", "Hawthorne", "Nellis Air Force Base", "Yerington",
        ],
        "New Hampshire": [
            "Manchester", "Nashua", "Concord", "East Concord", "Derry Village", "Dover",
            "Rochester", "Salem", "Merrimack", "Keene", "Derry", "Portsmouth",
            "Bedford", "Laconia", "Lebanon", "Windham", "Claremont", "Pelham",
            "Somersworth", "Londonderry", "Durham", "Hampton", "Berlin", "Exeter",
            "Milford", "Seabrook", "Hampstead", "Hanover", "Weare", "Franklin",
            "Barrington", "Bow Bog", "Litchfield", "Plaistow", "Gilford", "Hollis",
            "Pembroke", "Hudson", "Swanzey", "Stratham Station",
        ],
        "New Jersey": [
            "Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Trenton",
            "Toms River", "Clifton", "Camden", "Brick", "Passaic", "Cherry Hill",
            "Union City", "Bayonne", "Middletown", "East Orange", "North Bergen", "Irvington",
            "Vineland", "South Vineland", "Wayne", "New Brunswick", "Union", "Piscataway",
            "Jackson", "Lakewood", "Hoboken", "West New York", "Perth Amboy", "Plainfield",
            "Parsippany", "Bloomfield", "East Brunswick", "West Orange", "Sayreville", "Hackensack",
            "Bridgewater", "North Brunswick", "Sicklerville", "Sayreville Junction",
        ],
        "New Mexico": [
            "Albuquerque", "Las Cruces", "Enchanted Hills", "Rio Rancho", "Santa Fe", "Roswell",
            "Farmington", "South Valley", "Clovis", "Hobbs", "Alamogordo", "Carlsbad",
            "Gallup", "Sunland Park", "Los Lunas", "Chaparral", "Deming", "Las Vegas",
            "Artesia", "Los Alamos", "Portales", "Lovington", "North Valley", "Espanola",
            "Silver City", "Anthony", "Grants", "Bernalillo", "Socorro", "Corrales",
            "Shiprock", "Kirtland", "Ruidoso", "Bloomfield", "Belen", "Zuni Pueblo",
            "Raton", "Aztec", "Eldorado at Santa Fe", "Truth or Consequences",
        ],
        "New York": [
            "New York City", "Brooklyn", "Queens", "Manhattan", "The Bronx", "Staten Island",
            "Buffalo", "Upper West Side", "Jamaica", "Rochester", "Yonkers", "East Flatbush",
            "East New York", "Washington Heights", "Astoria", "Borough Park", "Syracuse", "Sunset Park",
            "Sheepshead Bay", "Amherst", "Harlem", "East Harlem", "Elmhurst", "Bushwick",
            "Gravesend", "Corona", "Albany", "Richmond Hill", "Fordham", "West Albany",
            "Flatbush", "Chinatown", "Canarsie", "Greenburgh", "New Rochelle", "South Ozone Park",
            "Cheektowaga", "Kings Bridge", "Brownsville", "Ridgewood",
        ],
        "North Carolina": [
            "Charlotte", "Raleigh", "West Raleigh", "Greensboro", "Durham", "Winston-Salem",
            "Fayetteville", "Cary", "Wilmington", "High Point", "Asheville", "Greenville",
            "Concord", "Gastonia", "Jacksonville", "Chapel Hill", "Rocky Mount", "Huntersville",
            "Burlington", "Wilson", "Kannapolis", "Apex", "Hickory", "Wake Forest",
            "Indian Trail", "Mooresville", "Goldsboro", "Monroe", "Salisbury", "Holly Springs",
            "Matthews", "New Bern", "Fort Bragg", "Sanford", "Cornelius", "Garner",
            "Thomasville", "Statesville", "Asheboro", "Mint Hill",
        ],
        "North Dakota": [
            "Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo", "Williston",
            "Dickinson", "Mandan", "Jamestown", "Wahpeton", "Devils Lake", "Watford City",
            "Valley City", "Minot Air Force Base", "Grafton", "Lincoln", "Beulah", "Rugby",
            "Stanley", "Horace", "Casselton", "New Town", "Hazen", "Grand Forks Air Force Base",
            "Bottineau", "Lisbon", "Belcourt", "Carrington", "Mayville", "Oakes",
            "Langdon", "Harvey", "Bowman", "Tioga", "Hillsboro", "Garrison",
            "Crosby", "New Rockford", "Park River", "Surrey",
        ],
        "Ohio": [
            "Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton",
            "Parma", "Canton", "Youngstown", "Lorain", "Hamilton", "Springfield",
            "Kettering", "Elyria", "Lakewood", "Cuyahoga Falls", "Middletown", "Newark",
            "Euclid", "Mentor", "Mansfield", "Beavercreek", "Dublin", "Cleveland Heights",
            "Strongsville", "Fairfield", "Findlay", "Warren", "Lancaster", "Grove City",
            "Westerville", "Huber Heights", "Delaware", "Lima", "Reynoldsburg", "Marion",
            "Boardman", "Upper Arlington", "Stow", "Brunswick",
        ],
        "Oklahoma": [
            "Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton", "Edmond",
            "Moore", "Midwest City", "Enid", "Stillwater", "Muskogee", "Bartlesville",
            "Owasso", "Shawnee", "Yukon", "Ardmore", "Ponca City", "Bixby",
            "Duncan", "Del City", "Jenks", "Sapulpa", "Mustang", "Sand Springs",
            "Bethany", "Altus", "Claremore", "El Reno", "McAlester", "Ada",
            "Durant", "Tahlequah", "Chickasha", "Miami", "Glenpool", "Woodward",
            "Elk City", "Okmulgee", "Choctaw", "Weatherford",
        ],
        "Oregon": [
            "Portland", "Eugene", "Salem", "Gresham", "Hillsboro", "Beaverton",
            "Bend", "Medford", "Springfield", "Corvallis", "Albany", "Tigard",
            "Aloha", "Lake Oswego", "Keizer", "Grants Pass", "Oregon City", "McMinnville",
            "Redmond", "Tualatin", "West Linn", "Woodburn", "Forest Grove", "Newberg",
            "Wilsonville", "Roseburg", "Klamath Falls", "Ashland", "Milwaukie", "Bethany",
            "Lents", "Hayesville", "Sherwood", "Altamont", "Happy Valley", "Central Point",
            "Canby", "Hermiston", "Pendleton", "Troutdale",
        ],
        "Pennsylvania": [
            "Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton",
            "Bethlehem", "Bensalem", "Lancaster", "Center City", "Abington", "Levittown",
            "Havertown", "Harrisburg", "Wharton", "Whitman", "Oxford Circle", "Altoona",
            "Penn Hills", "York", "State College", "Wilkes-Barre", "Olney", "West Oak Lane",
            "Norristown", "Chester", "Cobbs Creek", "Somerton", "Mount Lebanon", "Bustleton",
            "Overbrook", "Bethel Park", "Wayne", "Radnor", "Williamsport", "Monroeville",
            "Cranberry Township", "Holmesburg", "Drexel Hill", "Port Richmond",
        ],
        "Rhode Island": [
            "Providence", "Warwick", "Cranston", "Pawtucket", "East Providence", "Woonsocket",
            "Coventry", "Cumberland", "North Providence", "South Kingstown", "West Warwick", "Johnston",
            "North Kingstown", "Newport", "Bristol", "Smithfield", "Lincoln", "Central Falls",
            "Westerly", "Portsmouth", "Middletown", "Barrington", "Narragansett", "East Greenwich",
            "Newport East", "Valley Falls", "Warren", "North Smithfield", "North Scituate", "Greenville",
            "Wakefield-Peacedale", "Charlestown", "Hopkinton", "Cumberland Hill", "Tiverton", "Kingston",
            "Exeter", "West Greenwich", "Jamestown", "Foster",
        ],
        "South Carolina": [
            "Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Rock Hill", "Greenville",
            "Summerville", "Sumter", "Goose Creek", "Hilton Head Island", "Florence", "Spartanburg",
            "Hilton Head", "Myrtle Beach", "Aiken", "Greer", "Anderson", "Mauldin",
            "Greenwood", "North Augusta", "Taylors", "Saint Andrews", "Conway", "Easley",
            "Simpsonville", "Wade Hampton", "Lexington", "Socastee", "Hanahan", "Bluffton",
            "West Columbia", "North Myrtle Beach", "Clemson", "Seven Oaks", "Berea", "Gantt",
            "Five Forks", "Dentsville", "Ladson", "Fort Mill",
        ],
        "South Dakota": [
            "Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Mitchell",
            "Yankton", "Pierre", "Huron", "Spearfish", "Vermillion", "Brandon",
            "Box Elder", "Rapid Valley", "Ellsworth Air Force Base", "Madison", "Sturgis", "Belle Fourche",
            "Harrisburg", "Tea", "Dell Rapids", "Hot Springs", "Mobridge", "Canton",
            "Pine Ridge", "Milbank", "Hartford", "Lead", "Blackhawk", "Winner",
            "North Sioux City", "Dakota Dunes", "Colonial Pine Hills", "Sisseton", "Chamberlain", "Redfield",
            "Flandreau", "North Spearfish", "Lennox", "Summerset",
        ],
        "Tennessee": [
            "Nashville", "New South Memphis", "Memphis", "Knoxville", "Chattanooga", "Clarksville",
            "Murfreesboro", "East Chattanooga", "Franklin", "Cordova", "Jackson", "Johnson City",
            "Bartlett", "Hendersonville", "Kingsport", "Collierville", "Smyrna", "Cleveland",
            "Brentwood", "Germantown", "Hermitage", "Columbia", "Spring Hill", "La Vergne",
            "Gallatin", "Cookeville", "Mount Juliet", "Brentwood Estates", "Lebanon", "Morristown",
            "Oak Ridge", "Maryville", "Bristol", "Ellendale", "Farragut", "Shelbyville",
            "East Ridge", "Tullahoma", "Goodlettsville", "Springfield",
        ],
        "Texas": [
            "Houston", "San Antonio", "Dallas", "Fort Worth", "Austin", "El Paso",
            "Arlington", "Corpus Christi", "Plano", "Laredo", "Lubbock", "Garland",
            "Irving", "Cypress", "Amarillo", "Grand Prairie", "Brownsville", "McKinney",
            "Frisco", "Pasadena", "Mesquite", "Killeen", "McAllen", "Carrollton",
            "Midland", "Waco", "Denton", "Abilene", "Round Rock", "Beaumont",
            "Odessa", "Richardson", "Pearland", "College Station", "Wichita Falls", "Lewisville",
            "Tyler", "San Angelo", "Alief", "League City",
        ],
        "Utah": [
            "Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy Hills",
            "Sandy", "Ogden", "Layton", "Saint George", "South Jordan", "Millcreek",
            "Taylorsville", "Lehi", "Logan", "Murray", "Draper", "Bountiful",
            "Riverton", "Pleasant Grove", "Roy", "Spanish Fork", "South Jordan Heights", "Kearns",
            "Cottonwood Heights", "Tooele", "Midvale", "Springville", "Holladay", "Herriman",
            "Clearfield", "Kaysville", "Cedar City", "American Fork", "Syracuse", "Eagle Mountain",
            "Magna", "Saratoga Springs", "South Salt Lake", "Washington",
        ],
        "Vermont": [
            "Burlington", "South Burlington", "Colchester", "Rutland", "Essex Junction", "Hartford",
            "Bennington", "Barre", "Williston", "Montpelier", "St Johnsbury", "Brattleboro",
            "Winooski", "Saint Albans", "Middlebury (village)", "Saint Johnsbury", "Morristown", "Lyndon",
            "Rockingham", "Newport", "Hinesburg", "Stowe", "Springfield", "Charlotte",
            "Pownal", "Bellows Falls", "Chester", "Ferrisburgh", "West Brattleboro", "Vergennes",
            "Clarendon", "Swanton", "White River Junction", "White River Junction VA Medical Center", "Fair Haven", "Manchester Center",
            "Northfield", "Windsor", "Morrisville", "Bristol",
        ],
        "Virginia": [
            "Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Arlington", "Newport News",
            "Alexandria", "East Hampton", "Hampton", "Roanoke", "Portsmouth Heights", "Portsmouth",
            "Suffolk", "South Suffolk", "Lynchburg", "Centreville", "Dale City", "West Lynchburg",
            "Reston", "Harrisonburg", "Leesburg", "McLean", "Charlottesville", "Tuckahoe",
            "Blacksburg", "Ashburn", "Danville", "Manassas", "Lake Ridge", "Burke",
            "Annandale", "Mechanicsville", "Linton Hall", "Oakton", "Oak Hill", "Petersburg",
            "Springfield", "West Falls Church", "Fredericksburg", "Sterling",
        ],
        "Washington": [
            "Seattle", "Tri-Cities", "Spokane", "Tacoma", "Vancouver", "Bellevue",
            "Kent", "Everett", "Renton", "Federal Way", "Spokane Valley", "Yakima",
            "Kirkland", "Bellingham", "Kennewick", "Auburn", "Pasco", "Marysville",
            "Redmond", "Lakewood", "Olympia", "Shoreline", "Richland", "South Hill",
            "Sammamish", "Burien", "Lacey", "City of Sammamish", "Bothell", "Edmonds",
            "Puyallup", "Bremerton", "Lynnwood", "Longview", "Issaquah", "Parkland",
            "Mount Vernon", "West Lake Sammamish", "Wenatchee", "University Place",
        ],
        "Washington DC": [
            "Washington", "Downtown DC", "Columbia Heights", "Mount Pleasant", "Central 14th Street / Spring Road", "Northwest One",
            "Dupont Circle", "Foggy Bottom", "Mount Vernon Triangle", "H Street NE", "Pleasant Plains", "NoMa",
            "Petworth", "Capitol Riverfront", "Park View", "Golden Triangle", "Shaw", "Brightwood",
            "Adams Morgan", "Kennedy Street", "Southwest Waterfront", "Capitol Hill", "Barracks Row", "Union Market",
            "Georgetown", "Anacostia", "Colorado Triangle", "Brentwood Village", "The Wharf", "Central 14th Street / WMATA Northern Bus Barn",
            "Van Ness", "Benning Road", "Hillcrest", "Deanwood", "Woodley Park", "Cleveland Park",
            "Bellevue", "Chevy Chase", "Riggs Park", "Benning",
        ],
        "West Virginia": [
            "Huntington", "Charleston", "Parkersburg", "Morgantown", "Wheeling", "Weirton Heights",
            "Weirton", "Fairmont", "Martinsburg", "Beckley", "Clarksburg", "Teays Valley",
            "South Charleston", "Saint Albans", "Vienna", "Bluefield", "Cross Lanes", "Moundsville",
            "Bridgeport", "Oak Hill", "Cheat Lake", "Dunbar", "Elkins", "Nitro",
            "Pea Ridge", "Hurricane", "Princeton", "Charles Town", "Augusta", "Buckhannon",
            "Keyser", "New Martinsville", "Brookhaven", "Grafton", "Ranson", "Point Pleasant",
            "Westover", "Weston", "Barboursville", "Sissonville",
        ],
        "Wisconsin": [
            "Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton",
            "Waukesha", "Eau Claire", "Oshkosh", "Janesville", "West Allis", "La Crosse",
            "North La Crosse", "Sheboygan", "Wauwatosa", "Fond du Lac", "New Berlin", "Wausau",
            "Brookfield", "Greenfield", "Beloit", "Franklin", "Menomonee Falls", "Oak Creek",
            "Manitowoc", "Sun Prairie", "West Bend", "Fitchburg", "Stevens Point", "Superior",
            "Mount Pleasant", "Neenah", "Muskego", "De Pere", "Caledonia", "Watertown",
            "Mequon", "South Milwaukee", "Pleasant Prairie", "Germantown",
        ],
        "Wyoming": [
            "Cheyenne", "Casper", "Gillette", "Laramie", "Rock Springs", "Sheridan",
            "Green River", "Evanston", "Riverton", "Jackson", "Cody", "Rawlins",
            "Lander", "Torrington", "Douglas", "Powell", "Ranchettes", "Worland",
            "Buffalo", "South Greeley", "Mills", "Wheatland", "Fox Farm-College", "Newcastle",
            "Thermopolis", "Evansville", "Bar Nunn", "Kemmerer", "Glenrock", "Lovell",
            "North Rock Springs", "Lyman", "Afton", "Pinedale", "Greybull", "Wright",
            "Moose Wilson Road", "Fort Washakie", "South Park", "Saratoga",
        ],
    }
}
